spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userschema
    username: postgres
    password: 12345
  jpa:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  logging.level.root: DEBUG
server:
  port: 8080